### ISSUE TITLE
Restructure Ona forms to have separate forms for toilets and reports.

### ISSUE THREAD

**Issue by hodgestar** [praekelt/go-imali-yethu-js#35]
Currently there is one Ona form for reports. I propose switching to two forms:
### Per report form

The first form is _per report_ and is _private_.
- It is essentially the existing form with the phone number and City of Cape Town reference code added as fields.
- New reports will continue to be created whenever a report is submitted via the USSD application.
- The City of Cape Town reference code will initially be blank.
- The phone number will be automatically populated.
### Per toilet form

The second form is _per toilet_ and is _public_. It's fields are:
- `toilet_code`, `toilet_section`, `toilet_cluster`, `toilet_location`
- `toilet_status` (`no_issue` or `issue_reported`)
- `toilet_issue` (text field, blank if no issue, otherwise the reported issue)
- `toilet_issue_date` (blank or the date on which the issue was reported)
- This form will be _manually_ updated but will initially be populated with all the known toilets in a `no_issue` state.
### Design goals

This proposal was motivated by trying to:
- allow us to have both per-toilet and per-report records
- allow us to have both private and public data
- add the MSISDN and CoCT issue number as new fields

**Comment by rudigiesler** [comment]
Code changes implemented in https://github.com/praekelt/go-imali-yethu-js/pull/36 and https://github.com/praekelt/go-imali-yethu-js/pull/37

**Comment by hodgestar** [comment]
Addressed by #36 and #37.

**Comment by hodgestar** [comment]
And by #38, #39 and #40.
